name: Update & Publish public_price_stock

on:
  workflow_dispatch:
    inputs:
      force_run:
        description: "Bypass 72h gate and run now"
        type: boolean
        default: false
  schedule:
    - cron: "0 */12 * * *"         # checks every 12h; gate enforces ~72h
  push:
    branches: [ main ]
    paths:
      - "main.py"
      - "requirements.txt"
      - ".github/workflows/update.yml"
      - "docs/**"

permissions:
  contents: write
  deployments: write

concurrency:
  group: public-price-stock
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      CF_API_TOKEN:     ${{ secrets.CF_API_TOKEN }}
      CF_ACCOUNT_ID:    ${{ secrets.CF_ACCOUNT_ID }}
      CF_PROJECT_NAME:  ${{ secrets.CF_PROJECT_NAME }}
      TENANT_ID:        ${{ secrets.TENANT_ID }}
      CLIENT_ID:        ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET:    ${{ secrets.CLIENT_SECRET }}
      SP_SITE_HOSTNAME: ${{ secrets.SP_SITE_HOSTNAME }}
      SP_SITE_PATH:     ${{ secrets.SP_SITE_PATH }}
      SP_XLSX_PATH:     ${{ secrets.SP_XLSX_PATH }}
      SP_TABLE_NAME:    ${{ secrets.SP_TABLE_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Decide whether to run (>=72h gate or force)
        id: gate
        shell: bash
        run: |
          set -euo pipefail
          FORCE="${{ github.event.inputs.force_run || 'false' }}"
          FILE="docs/public_price_stock.xml"
          if [ "$FORCE" = "true" ]; then
            echo "run=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          if [ ! -f "$FILE" ]; then
            echo "run=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          LAST_TS=$(git log -1 --format=%ct -- "$FILE" || echo 0)
          NOW_TS=$(date +%s)
          ELAPSED=$(( NOW_TS - LAST_TS ))
          echo "Last update: $ELAPSED seconds ago"
          # 72h ~= 259200; allow ~1h slack (255600)
          if [ "$ELAPSED" -ge 255600 ]; then
            echo "run=true" >> $GITHUB_OUTPUT
          else
            echo "run=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Python
        if: steps.gate.outputs.run == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        if: steps.gate.outputs.run == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate XML
        if: steps.gate.outputs.run == 'true'
        run: python main.py

      - name: Commit & push if changed
        if: steps.gate.outputs.run == 'true'
        run: |
          set -e
          if [[ -n "$(git status --porcelain docs/public_price_stock.xml)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/public_price_stock.xml
            git commit -m "Update public_price_stock.xml"
            git push
          else
            echo "No content changes to commit."
          fi

      - name: Deploy /docs to Cloudflare Pages
        if: steps.gate.outputs.run == 'true'
        uses: cloudflare/pages-action@v1
        with:
          apiToken:    ${{ secrets.CF_API_TOKEN }}
          accountId:   ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ secrets.CF_PROJECT_NAME }}
          directory:   docs

      - name: Skipped (gate)
        if: steps.gate.outputs.run != 'true'
        run: echo "⏭️ Skipped: last publish was <72h ago."
