name: Update & Publish public_price_stock

on:
  workflow_dispatch:
    inputs:
      force_run:
        description: 'Run immediately (ignore 72h gate)'
        required: false
        default: false
        type: boolean
  push:
    branches: [main]
  schedule:
    - cron: '0 */12 * * *'

permissions:
  contents: write
  deployments: write

concurrency:
  group: public-price-stock
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      CF_API_TOKEN:     ${{ secrets.CF_API_TOKEN }}
      CF_ACCOUNT_ID:    ${{ secrets.CF_ACCOUNT_ID }}
      CF_PROJECT_NAME:  ${{ secrets.CF_PROJECT_NAME }}
      TENANT_ID:        ${{ secrets.TENANT_ID }}
      CLIENT_ID:        ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET:    ${{ secrets.CLIENT_SECRET }}
      SP_SITE_HOSTNAME: ${{ secrets.SP_SITE_HOSTNAME }}
      SP_SITE_PATH:     ${{ secrets.SP_SITE_PATH }}
      SP_XLSX_PATH:     ${{ secrets.SP_XLSX_PATH }}
      SP_TABLE_NAME:    ${{ secrets.SP_TABLE_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate XML
        run: python main.py

      - name: Commit and push if changed
        run: |
          if [[ -n "$(git status --porcelain docs/public_price_stock.xml)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/public_price_stock.xml
            git commit -m "Update public_price_stock.xml"
            git push
          else
            echo "No changes to commit"
          fi

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken:    ${{ secrets.CF_API_TOKEN }}
          accountId:   ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ secrets.CF_PROJECT_NAME }}
          directory:   docs
